### ISSUE TITLE
New Leaf 2019 Protocol

### ISSUE THREAD

**Issue by cedric222** [gboudreau/nissan-connect-php#29]
Hi,

I replace my old leaf 2016, with a very new 2019, and the new apps is "Nissan Connect Services" and no more "Nissan Connect EV". 
Unfortunately, I have now a http 408 error with nissan-connect-php... do you know if someone already try to reverse engineering this new apps ?

thanks

cedric

**Comment by Raiden38** [comment]
Use the New API, I have a 2018 and it works fine!

**Comment by gboudreau** [comment]
https://github.com/gboudreau/nissan-connect-php/tree/new-api

**Comment by cedric222** [comment]
I will try. @Raiden38 do your cars works with "Nissan Connect Services" ? ( and not "Nissan Connect EV" ) Since April 2019, and the new 8 inch screen, seems there is some change.

**Comment by Raiden38** [comment]
It written Nissan Connect EV & Services lol. Should be the latest version. I have the 8 inch screen also. Try the new API and let us know

**Comment by howartp84** [comment]
2019 uses a new API from May onwards ("Nissan Connect Services"), which nobody has yet decoded and implemented yet to my knowledge. Tobias at MyLeaf is on with it, with my credentials for testing.

**Comment by cedric222** [comment]
Sorry for the delay ! I don't have many time recently

Thanks @howartp84 for the info, let us know.

I test with the branch  "new-api", and the result here is
[2019-09-29 00:09:39][DEBUG] : [NissanConnect] Request: POST https://gdcportalgw.its-mo.com/api_v190426_NE/gdc/InitialApp_v2.php {"custom_sessionid":"","initial_app_str":"9s5rfKVuMrT03RtzajWNcA","RegionCode":"NE","lg":"en-US","DCMID":"","VIN":"","tz":"Europe\/Paris"}
[2019-09-29 00:09:49][DEBUG] : [NissanConnect] Response: {"status":200,"message":"success","baseprm":"88dSp7wWnV3xxxxxxxxxxx"}
[2019-09-29 00:09:49][DEBUG] : [NissanConnect] Request: POST https://gdcportalgw.its-mo.com/api_v190426_NE/gdc/UserLoginRequest.php {"UserId":"me@hotmail.com","Password":"toto","custom_sessionid":"","initial_app_str":"9s5rfKVuMrT03RtzajWNcA","RegionCode":"NE","lg":"en-US","DCMID":"","VIN":"","tz":"Europe\/Paris"}
[2019-09-29 00:09:53][DEBUG] : [NissanConnect] Found resultKey in response:
[2019-09-29 00:09:53][DEBUG] : [NissanConnect] Request for 'UserLoginRequest.php' failed. Response received: {"status":"-2010","message":"INVALID PARAMS","resultKey":""} Will retry.
[20

The good new is the 2019 official apps is now usable, you can start heater in less then 20 seconds.. ( was more than 2 minutes with the 2016 Leaf apps )

**Comment by pirracas77** [comment]
I have this error

`Request` for 'UserLoginRequest.php' failed. Response received: {"status":"-2010","message":"INVALID PARAMS","resultKey":""}


Is it fixed in any realese?

**Comment by gboudreau** [comment]
I am myself using the `new-api` branch, which stopped working a while age (see #32).
The master branch, I can't use for quite a while. Not sure if it is working for anyone.

**Comment by pirracas77** [comment]
Thanks with the quick answer. 
Whit thje new-api I get
`Login failed, or failed to find car VIN, authToken or accountID in response of login request: {"errorMessage":"Authentication Failure","errorCode":910,"status":200}`

**Comment by andig** [comment]
I'm developing a PV-controlled EV charger at https://github.com/andig/evcc and would like to support the newer Nissans. If I understand correctly the protocol has not been decoded yet? Are you aware of https://github.com/gboudreau/LEAF_Carwings_EasyAccess/issues/8#issuecomment-520143453 and does that work? Also here is an explicit reference to Nissan Connect which seems to be the "new" api: https://github.com/Tobiaswk/dartnissanconnectna

**Comment by gboudreau** [comment]
@andig The correct code to use to connect to the API might depend on region (EU, North America, Japan). I'm in Canada, and was using the new-api branch until it stopped working a while ago. I didn't take the time to reverse engineer the Android app, to see what was wrong with my code.
I was recently told that the code available at https://gitlab.com/tobiaswkjeldsen/carwingsflutter you might look there to get a working code example; I didn't yet take the time to look myself.

**Comment by gboudreau** [comment]
Follow up: so the new-api branch is working now; that branch should fix it for North America (it is working for my 2011 MY in Canada).
For 2019+, I think a completely different API is required, but I'm not sure if it applies worldwide, or only in specific regions.
Anyone has a 2019+ LEAF, and could test the new-api branch, and report if it works, and in which region they are?

**Comment by pirracas77** [comment]
> Follow up: so the new-api branch is working now; that branch should fix it for North America (it is working for my 2011 MY in Canada).
> For 2019+, I think a completely different API is required, but I'm not sure if it applies worldwide, or only in specific regions.
> Anyone has a 2019+ LEAF, and could test the new-api branch, and report if it works, and in which region they are?

For me is still not working (2019+ , Europe)

`×Login failed, or failed to find car VIN, authToken or accountID in response of login request: {"errorMessage":"Authentication Failure","errorCode":910,"status":200}
`

**Comment by gboudreau** [comment]
OK, so I guess you'd need completely new code, something like this: https://github.com/Tobiaswk/dartnissanconnect/tree/master/lib/src
That code connects to Kamereon platform in EU.
If anyone wants to modify the code to replicate Tobiaswk's code, I'd be happy to review any PR.

**Comment by pirracas77** [comment]
Here there is a TypeScript port if anyone is interested.

https://github.com/sebjsmith/kamereon
